name: 'Setup Workspace'
description: 'Checkout code, setup Node.js with pnpm, and install dependencies'

inputs:
  npm-token:
    description: 'NPM token for authentication'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      with:
        node-version-file: package.json
        cache: "pnpm"
        always-auth: "true"
        scope: "@plextv"
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
