name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  release:
    name: Release
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all commit history for generating the changelog.
          fetch-depth: 0
          # Avoid configuring the token with the local git config in favor of
          # our own environment token (see below).
          persist-credentials: false

      - uses: pnpm/action-setup@v4

      - uses: buildjet/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Set up environment
        uses: ./.github/actions/setup
        timeout-minutes: 5

      - name: Create release pull request or publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          commit: "chore: Update versions"
          title: "chore: Update versions"
          publish: pnpm run ci:publish
        env:
          # When you use the repository's GITHUB_TOKEN to perform tasks, events
          # triggered by the GITHUB_TOKEN will not create a new workflow run.
          # This means that checks won't run on the release PRs. We work around
          # this by using our own GH_TOKEN_REPO_ACCESS organization secret.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO_ACCESS }}
